import pygame,os
pygame.init()
absolute_path = os.path.dirname(__file__)
swidth,sheight = 1200,600
s = pygame.display.set_mode((swidth,sheight))

#SURFACES:
title_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
backstory_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
play_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
camera_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
notice_board_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
notice_board_open_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
sonar_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
power_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
pda_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
battery_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
sonar_view_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
base_scan_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)
base_data_surface = pygame.Surface((swidth,sheight),pygame.SRCALPHA)

#IMAGES:
#backgrounds:
title_bg = pygame.image.load(absolute_path + r'\assets\images\backgrounds\new_title_screen.png').convert_alpha()
title_bg = pygame.transform.scale(title_bg,(swidth,sheight))
backstory_bg = pygame.image.load(absolute_path + r'\assets\images\backgrounds\backstory.png').convert_alpha()
backstory_bg = pygame.transform.scale(backstory_bg,(swidth,sheight))
main_view_bg = pygame.image.load(absolute_path + r'\assets\images\backgrounds\main_view.png').convert_alpha()
main_view_bg = pygame.transform.scale(main_view_bg,(swidth,sheight))
main_view_bg_LO = pygame.image.load(absolute_path + r'\assets\images\backgrounds\main_view_LO.png').convert_alpha()
main_view_bg_LO = pygame.transform.scale(main_view_bg_LO,(swidth,sheight))
camera_bg = pygame.image.load(absolute_path + r'\assets\images\backgrounds\camera_view.png').convert_alpha()
camera_bg = pygame.transform.scale(camera_bg,(swidth,sheight))
camera_bg_LO = pygame.image.load(absolute_path + r'\assets\images\backgrounds\camera_view_LO.png').convert_alpha()
camera_bg_LO = pygame.transform.scale(camera_bg_LO,(swidth,sheight))

#tablet screens:
play_bg = pygame.image.load(absolute_path + r'\assets\images\tablet_screens\play_screen.png').convert_alpha()
play_bg = pygame.transform.scale(play_bg,(swidth,sheight))
play_bg_LO = pygame.image.load(absolute_path + r'\assets\images\tablet_screens\play_screen_LO.png').convert_alpha()
play_bg_LO = pygame.transform.scale(play_bg_LO,(swidth,sheight))
sonar_bg = pygame.image.load(absolute_path + r'\assets\images\tablet_screens\sonarscreen.png').convert_alpha()
sonar_bg = pygame.transform.scale(sonar_bg,(swidth,sheight))
sonar_bg_LO = pygame.image.load(absolute_path + r'\assets\images\tablet_screens\sonarscreen_LO.png').convert_alpha()
sonar_bg_LO = pygame.transform.scale(sonar_bg_LO,(swidth,sheight))
sonar_offline_bg = pygame.image.load(absolute_path + r'\assets\images\tablet_screens\sonarscreen_offline.png').convert_alpha()
sonar_offline_bg = pygame.transform.scale(sonar_offline_bg,(swidth,sheight))
power_bg = pygame.image.load(absolute_path + r'\assets\images\tablet_screens\batteryscreen.png').convert_alpha()
power_bg = pygame.transform.scale(power_bg,(swidth,sheight))
power_bg_LO = pygame.image.load(absolute_path + r'\assets\images\tablet_screens\batteryscreen_LO.png').convert_alpha()
power_bg_LO = pygame.transform.scale(power_bg_LO,(swidth,sheight))
pda_bg = pygame.image.load(absolute_path + r'\assets\images\tablet_screens\pdascreen.png').convert_alpha()
pda_bg = pygame.transform.scale(pda_bg,(swidth,sheight))
pda_bg_LO = pygame.image.load(absolute_path + r'\assets\images\tablet_screens\pdascreen_LO.png').convert_alpha()
pda_bg_LO = pygame.transform.scale(pda_bg_LO,(swidth,sheight))


#background rectangles:
title_bg_rect = title_bg.get_rect()
backstory_bg_rect = backstory_bg.get_rect()
play_bg_rect = play_bg.get_rect()
camera_bg_rect = camera_bg.get_rect()
main_view_bg_rect =main_view_bg.get_rect()
sonar_bg_rect = sonar_bg.get_rect()
sonar_offline_bg_rect = sonar_offline_bg.get_rect()
power_bg_rect = power_bg.get_rect()
pda_bg_rect = pda_bg.get_rect()


#assets:
battery_img6 = pygame.image.load(absolute_path + r'\assets\images\extras\battery_6.png').convert_alpha()
battery_img6 = pygame.transform.scale(battery_img6,(200,240))
battery_img5 = pygame.image.load(absolute_path + r'\assets\images\extras\battery_5.png').convert_alpha()
battery_img5 = pygame.transform.scale(battery_img5,(200,240))
battery_img4 = pygame.image.load(absolute_path + r'\assets\images\extras\battery_4.png').convert_alpha()
battery_img4 = pygame.transform.scale(battery_img4,(200,240))
battery_img3 = pygame.image.load(absolute_path + r'\assets\images\extras\battery_3.png').convert_alpha()
battery_img3 = pygame.transform.scale(battery_img3,(200,240))
battery_img2 = pygame.image.load(absolute_path + r'\assets\images\extras\battery_2.png').convert_alpha()
battery_img2 = pygame.transform.scale(battery_img2,(200,240))
battery_img1 = pygame.image.load(absolute_path + r'\assets\images\extras\battery_1.png').convert_alpha()
battery_img1 = pygame.transform.scale(battery_img1,(200,240))
battery_img0 = pygame.image.load(absolute_path + r'\assets\images\extras\battery_0.png').convert_alpha()
battery_img0 = pygame.transform.scale(battery_img0,(200,240))
OM4 = pygame.image.load(absolute_path + r'\assets\images\extras\OM4.png').convert_alpha()
OM4 = pygame.transform.scale(OM4,(120,60))
OM4_LO = pygame.image.load(absolute_path + r'\assets\images\extras\OM4_LO.png').convert_alpha()
OM4_LO = pygame.transform.scale(OM4_LO,(120,60))
OM3 = pygame.image.load(absolute_path + r'\assets\images\extras\OM3.png').convert_alpha()
OM3 = pygame.transform.scale(OM3,(100,50))
OM3_LO = pygame.image.load(absolute_path + r'\assets\images\extras\OM3_LO.png').convert_alpha()
OM3_LO = pygame.transform.scale(OM3_LO,(120,60))
OM2 = pygame.image.load(absolute_path + r'\assets\images\extras\OM2.png').convert_alpha()
OM2 = pygame.transform.scale(OM2,(100,50))
OM2_LO = pygame.image.load(absolute_path + r'\assets\images\extras\OM2_LO.png').convert_alpha()
OM2_LO = pygame.transform.scale(OM2_LO,(120,60))
OM1 = pygame.image.load(absolute_path + r'\assets\images\extras\OM1.png').convert_alpha()
OM1 = pygame.transform.scale(OM1,(100,50))
OM1_LO = pygame.image.load(absolute_path + r'\assets\images\extras\OM1_LO.png').convert_alpha()
OM1_LO = pygame.transform.scale(OM1_LO,(120,60))
OM0 = pygame.image.load(absolute_path + r'\assets\images\extras\OM0.png').convert_alpha()
OM0 = pygame.transform.scale(OM0,(100,50))
OM0_LO = pygame.image.load(absolute_path + r'\assets\images\extras\OM0_LO.png').convert_alpha()
OM0_LO = pygame.transform.scale(OM0_LO,(120,60))

scan_checkText_img = pygame.image.load(absolute_path + r'\assets\images\extras\scan_checkText.png').convert_alpha()
scan_checkText_img = pygame.transform.scale(scan_checkText_img,(246,88))
impact_Text_img = pygame.image.load(absolute_path + r'\assets\images\extras\impact_Text.png').convert_alpha()
impact_Text_img = pygame.transform.scale(impact_Text_img,(360,93))
log1 = pygame.image.load(absolute_path + r'\assets\images\log_things\scan_logs\log1_text.png').convert_alpha()
log1 = pygame.transform.scale(log1,(1200,600))
log2 = pygame.image.load(absolute_path + r'\assets\images\log_things\scan_logs\log2_text.png').convert_alpha()
log2 = pygame.transform.scale(log2,(1200,600))
log3 = pygame.image.load(absolute_path + r'\assets\images\log_things\scan_logs\log3_text.png').convert_alpha()
log3 = pygame.transform.scale(log3,(1200,600))
log4 = pygame.image.load(absolute_path + r'\assets\images\log_things\scan_logs\log4_text.png').convert_alpha()
log4 = pygame.transform.scale(log4,(1200,600))
log5 = pygame.image.load(absolute_path + r'\assets\images\log_things\scan_logs\log5_text.png').convert_alpha()
log5 = pygame.transform.scale(log5,(1200,600))
log6 = pygame.image.load(absolute_path + r'\assets\images\log_things\scan_logs\log6_text.png').convert_alpha()
log6 = pygame.transform.scale(log6,(1200,600))
log7 = pygame.image.load(absolute_path + r'\assets\images\log_things\scan_logs\log7_text.png').convert_alpha()
log7 = pygame.transform.scale(log7,(1200,600))

data1 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data1_text.png').convert_alpha()
data1 = pygame.transform.scale(data1,(1200,600))
data2 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data2_text.png').convert_alpha()
data2 = pygame.transform.scale(data2,(1200,600))
data3 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data3_text.png').convert_alpha()
data3 = pygame.transform.scale(data3,(1200,600))
data4 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data4_text.png').convert_alpha()
data4 = pygame.transform.scale(data4,(1200,600))
data5 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data5_text.png').convert_alpha()
data5 = pygame.transform.scale(data5,(1200,600))
data6 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data6_text.png').convert_alpha()
data6 = pygame.transform.scale(data6,(1200,600))
data7 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data7_text.png').convert_alpha()
data7 = pygame.transform.scale(data7,(1200,600))
data8 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data8_text.png').convert_alpha()
data8 = pygame.transform.scale(data8,(1200,600))
data9 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data9_text.png').convert_alpha()
data9 = pygame.transform.scale(data9,(1200,600))
data10 = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data10_text.png').convert_alpha()
data10 = pygame.transform.scale(data10,(1200,600))

indicator_pic = pygame.image.load(absolute_path + r'\assets\images\extras\indicator.png').convert_alpha()
indicator_pic = pygame.transform.scale(indicator_pic,(50,50))
indicator_pic.set_alpha(191)
LMB_indicator_pic = pygame.image.load(absolute_path + r'\assets\images\extras\LMB_indicator.png').convert_alpha()
LMB_indicator_pic = pygame.transform.scale(LMB_indicator_pic,(50,50))
log_scanButton = pygame.image.load(absolute_path + r'\assets\images\log_things\scan_logs\scan_logButton.png').convert_alpha()
log_scanButton = pygame.transform.scale(log_scanButton,(320,50))
log_dataButton = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\data_logButton.png').convert_alpha()
log_dataButton = pygame.transform.scale(log_dataButton,(320,40))

fade_img = pygame.image.load(absolute_path + r'\assets\images\extras\fade.png').convert_alpha()
fade_img = pygame.transform.scale(fade_img,(1200,600))
darken = pygame.image.load(absolute_path + r'\assets\images\extras\darken.png').convert_alpha()
darken = pygame.transform.scale(darken,(1200,600))
vignette = pygame.image.load(absolute_path + r'\assets\images\backgrounds\vignette.png').convert_alpha()
vignette = pygame.transform.scale(vignette,(1200,600))

#notice board images
MissionB = pygame.image.load(absolute_path + r'\assets\images\notices\MB.png').convert_alpha()
MissionB = pygame.transform.scale(MissionB,(415,615))
sMissionB = pygame.transform.scale(MissionB,(144,256))
RoverSB = pygame.image.load(absolute_path + r'\assets\images\notices\RSB.png').convert_alpha()
RoverSB = pygame.transform.scale(RoverSB,(415,615))
sRoverSB = pygame.transform.scale(RoverSB,(144,256))
TabletC1 = pygame.image.load(absolute_path + r'\assets\images\notices\TC1.png').convert_alpha()
TabletC1 = pygame.transform.scale(TabletC1,(415,615))
sTabletC1 = pygame.transform.scale(TabletC1,(144,256))
TabletC2 = pygame.image.load(absolute_path + r'\assets\images\notices\TC2.png').convert_alpha()
TabletC2 = pygame.transform.scale(TabletC2,(415,615))
EnvI1 = pygame.image.load(absolute_path + r'\assets\images\notices\EI1.png').convert_alpha()
EnvI1 = pygame.transform.scale(EnvI1,(415,615))
sEnvI1 = pygame.transform.scale(EnvI1,(144,256))
EnvI2 = pygame.image.load(absolute_path + r'\assets\images\notices\EI2.png').convert_alpha()
EnvI2 = pygame.transform.scale(EnvI2,(415,615))
LiabF = pygame.image.load(absolute_path + r'\assets\images\notices\LF.png').convert_alpha()
LiabF = pygame.transform.scale(LiabF,(415,615))
sLiabF = pygame.transform.scale(LiabF,(144,256))
CrumpN1 = pygame.image.load(absolute_path + r'\assets\images\notices\CN1.png').convert_alpha()
CrumpN1 = pygame.transform.scale(CrumpN1,(415,615))
sCrumpN1 = pygame.transform.scale(CrumpN1,(144,256))
CrumpN2 = pygame.image.load(absolute_path + r'\assets\images\notices\CN2.png').convert_alpha()
CrumpN2 = pygame.transform.scale(CrumpN2,(415,615))

#LOG NOTES:
#Scan Logs:
base_scan = pygame.image.load(absolute_path + r'\assets\images\log_things\scan_logs\base_scanScreen.png').convert_alpha()
base_scan = pygame.transform.scale(base_scan,(1200,600))
base_data = pygame.image.load(absolute_path + r'\assets\images\log_things\data_logs\base_dataScreen.png').convert_alpha()
base_data = pygame.transform.scale(base_data,(1200,600))

#background rectangles:
base_scan_rect = base_scan.get_rect()
base_data_rect = base_data.get_rect()

#SOUND EFFECTS / MUSIC:
#Channels:

bg_audio = pygame.mixer.Channel(1)
additionals1 = pygame.mixer.Channel(2)
additionals2 = pygame.mixer.Channel(3)


bg_audio.set_volume(0)
additionals1.set_volume(0)
additionals2.set_volume(0)


#Sounds:
rv_ambiance = pygame.mixer.Sound(absolute_path + r'\assets\audio\rover_ambiance.wav')
rv_moving = pygame.mixer.Sound(absolute_path + r'\assets\audio\rover_moving.wav')
ts_wind = pygame.mixer.Sound(absolute_path + r'\assets\audio\title_screen_wind.wav')
ts_gc = pygame.mixer.Sound(absolute_path + r'\assets\audio\title_screen_geiger_counter.wav')
ts_gc.set_volume(0.6)